instances:
  - name: "monitoringksvr0"
    ip: 
      - "10.20.40.7"
    dns: 
      - "monitoringksvr0.dom.co.uk"
  - name: "monitoringesvr0"
    ip:
      - "10.20.30.11"
    dns:
      - "monitoringesvr0.dom.co.uk"
  - name: "monitoringesvr1"
    ip:
      - "10.20.30.7"
    dns:
      - "monitoringesvr1.dom.co.uk"
